### ISSUE TITLE
RemoveProvider implementation in persistence

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/go-indexer-core#14]
If we need to remove all data for a provider in the persistence layer there's no implementation for it yet.

https://github.com/filecoin-project/go-indexer-core/blob/913aef796c01b8da2188d0ad18b83ed279deb412/store/storethehash/storethehash.go#L186

It may require an offline process that iterates through memory checking all CIDs that have metadata for that provider. Maybe we can also design a new index that keeps track of providers and CIDs to optimize this process (it may add a significant storage overhead, we'll need to benchmark it)

**Comment by gammazero** [comment]
Fixed by #35
