### ISSUE TITLE
track bitsize used in storethehash setup

### ISSUE THREAD

**Issue by willscott** [filecoin-project/go-indexer-core#62]
currently a bitsize option is allowed, but if the index is subsequently opened with a different bitsize set, bad things will happen.
the used bitsize should be persisted somewhere with a store the hash datastore.

**Comment by masih** [comment]
Having auto-migration option would also be useful, where the user can choose whether to automatically migrate the existing data to the new bitsize or error out with a well-known error.

**Comment by gammazero** [comment]
This is tracked within storethehash. If sth is started with a different bitsize than was previously used, an error is generated:
https://github.com/ipld/go-storethehash/blob/master/store/index/index.go#L189-L190

**Comment by gammazero** [comment]
Closing this, and opening auto-migration issue here: https://github.com/ipld/go-storethehash/issues/78
